# Generated by Django 4.2 on 2024-11-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_post_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="video",
            field=models.FileField(
                blank=True,
                default="../default_video_n6ie5w",
                null=True,
                upload_to="videos/",
            ),
        ),
    ]
