# Generated by Django 4.2 on 2024-11-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_alter_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, default="../default_post_ftw1xc", upload_to="images/"
            ),
        ),
    ]
