# Generated by Django 4.2 on 2024-11-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_hashtag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='posts',
        ),
        migrations.AddField(
            model_name='post',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='posts.hashtag'),
        ),
    ]
