# Generated by Django 4.2 on 2024-11-09 13:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0010_remove_hashtag_posts_post_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mentions',
            field=models.ManyToManyField(blank=True, related_name='mentions_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
