# Generated by Django 4.2 on 2024-11-23 21:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('direct_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='directmessage',
            unique_together={('sender', 'receiver')},
        ),
    ]
