# Generated by Django 4.2 on 2024-11-24 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direct_messages', '0002_alter_directmessage_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='directmessage',
            unique_together=set(),
        ),
    ]
